class_name Global
extends Node

const SUSPICION_DECAY_PER_SEC = 2.0
const SUSPICION_PLAYER_BROKE_ORE = 20.0
const SUSPICION_PLAYER_NOT_ON_SLOT = 40.0
const SUSPICION_STOLE_GOLD = 40.0
const SUSPICION_TRESHOLD = 95.0
const SUSPICION_DECAY_PROCESS_ORE = 10.0

const STACK_EMPTY_TO_BREAK = 3

const PLAYER_INDEX = 6

const COWORKER_INIT_NUMBER = 5

const ITEM_DURATION = 15.0
const KNOCKOUT_TIME = 5.0
